/* JUAN PROJECT Workspace V1.3 */
(()=>{
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  let draftId=null,drafts=[];
  async function adminSession(){const cfg=await fetch('/api/supabase-config',{cache:'no-store'}).then(r=>r.json());if(!window.__jpV13Sb)window.__jpV13Sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true}});return (await window.__jpV13Sb.auth.getSession()).data.session}
  async function draftApi(method='GET',body){const ses=await adminSession();if(!ses)throw Error('Admin log in required.');const r=await fetch('/api/drafts',{method,headers:{Authorization:`Bearer ${ses.access_token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Draft request failed.');return j}
  function collect(){const gv=id=>$(id)?.value??'',ck=id=>!!$(id)?.checked;return {project_name:gv('#orderProjectName'),existing_client_id:gv('#orderClientSelect'),existing_client_search:gv('#orderClientSearch'),new_client_name:gv('#newClientName'),new_client_email:gv('#newClientEmail'),new_client_phone:gv('#newClientPhone'),new_client_address:gv('#newClientAddress'),start_date:gv('#orderStartDate'),deadline_date:gv('#orderDeadlineDate'),priority:ck('#priorityProjectToggle'),notes:gv('#orderNotes'),client_mode:$('#clientNewMode')?.classList.contains('hidden')?'existing':'new'}}
  function hydrate(d){const set=(id,v)=>{const el=$(id);if(el)el.value=v??''};set('#orderProjectName',d.project_name);set('#orderClientSelect',d.existing_client_id);set('#orderClientSearch',d.existing_client_search);set('#newClientName',d.new_client_name);set('#newClientEmail',d.new_client_email);set('#newClientPhone',d.new_client_phone);set('#newClientAddress',d.new_client_address);set('#orderStartDate',d.start_date);set('#orderDeadlineDate',d.deadline_date);set('#orderNotes',d.notes);const pr=$('#priorityProjectToggle');if(pr)pr.checked=!!d.priority;if(window.app?.setClientMode)window.app.setClientMode(d.client_mode==='new'?'new':'existing')}
  function ensureModal(){if($('#jpDraftModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="jpDraftModal"><div class="modal-card v13-drafts-modal"><div class="modal-header"><div><div class="section-kicker">NEW ORDER</div><h3 class="modal-title">Draft Orders</h3></div><button class="modal-close" id="jpDraftClose">×</button></div><div id="jpDraftList" class="draft-list"></div></div></div>`);$('#jpDraftClose').onclick=()=>$('#jpDraftModal').classList.remove('show')}
  async function loadDrafts(){ensureModal();$('#jpDraftList').innerHTML='<div class="draft-empty">Loading drafts…</div>';$('#jpDraftModal').classList.add('show');try{drafts=(await draftApi()).drafts||[];renderDrafts()}catch(e){$('#jpDraftList').innerHTML=`<div class="draft-empty">${e.message}</div>`}}
  function renderDrafts(){const box=$('#jpDraftList');box.innerHTML=drafts.length?drafts.map(d=>`<div class="draft-row"><div><strong>${escapeHtml(d.project_name||d.title||'Untitled Draft')}</strong><span>${escapeHtml(d.client_name||'Client not selected')} · Saved ${new Date(d.updated_at||d.created_at).toLocaleString('en-PH',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</span></div><div><button class="btn btn-secondary btn-sm" data-resume-draft="${d.id}">Resume</button><button class="btn btn-text btn-sm text-danger" data-delete-draft="${d.id}">Delete</button></div></div>`).join(''):'<div class="draft-empty"><strong>No saved drafts</strong><span>Use Save Draft while preparing a new order.</span></div>';$$('[data-resume-draft]').forEach(b=>b.onclick=()=>resume(b.dataset.resumeDraft));$$('[data-delete-draft]').forEach(b=>b.onclick=()=>remove(b.dataset.deleteDraft))}
  const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  async function save(){const d=collect(),title=d.project_name||'Untitled Draft';const body={id:draftId,title,client_name:d.client_mode==='new'?d.new_client_name:d.existing_client_search,project_name:d.project_name,draft_data:d};try{const j=await draftApi('POST',body);draftId=j.draft.id;window.app?.showToast?.('Draft saved.')||console.log('Draft saved')}catch(e){alert(e.message)}}
  function resume(id){const row=drafts.find(x=>String(x.id)===String(id));if(!row)return;draftId=row.id;$('#jpDraftModal').classList.remove('show');window.app?.navigateTo?.('new-order');setTimeout(()=>hydrate(row.draft_data||{}),60)}
  async function remove(id){if(!confirm('Delete this draft?'))return;try{await draftApi('POST',{action:'delete',id});drafts=drafts.filter(x=>String(x.id)!==String(id));renderDrafts()}catch(e){alert(e.message)}}
  function mobileNav(){if($('#jpMobileWorkspaceNav'))return;document.body.insertAdjacentHTML('beforeend',`<nav id="jpMobileWorkspaceNav" class="mobile-workspace-nav"><button data-v="my-works">Home</button><button data-v="projects">Projects</button><button data-v="payments">Payments</button><button data-v="clients">Clients</button><button id="jpMobileMore">More</button></nav><div id="jpMobileMoreSheet" class="mobile-more-sheet"><div class="mobile-more-card"><div class="mobile-more-head"><strong>Workspace</strong><button id="jpMobileMoreClose">×</button></div><button data-v="new-order">New Order</button><button id="jpMobileDrafts">Drafts</button><button data-v="pricelist">Shop</button><button data-v="online-portal">Online Portal</button><button data-v="reports">Reports</button><button data-v="calendar">Calendar</button><button data-v="settings">Settings</button></div></div>`);$$('#jpMobileWorkspaceNav [data-v],#jpMobileMoreSheet [data-v]').forEach(b=>b.onclick=()=>{window.app?.navigateTo?.(b.dataset.v);$('#jpMobileMoreSheet').classList.remove('show')});$('#jpMobileMore').onclick=()=>$('#jpMobileMoreSheet').classList.add('show');$('#jpMobileMoreClose').onclick=()=>$('#jpMobileMoreSheet').classList.remove('show');$('#jpMobileDrafts').onclick=()=>{loadDrafts();$('#jpMobileMoreSheet').classList.remove('show')}}
  function install(){const d=$('#openDraftsBtn'),s=$('#saveDraftBtn');if(d)d.onclick=loadDrafts;if(s)s.onclick=save;mobileNav();const brand=$('.sidebar-brand-subtitle');if(brand)brand.textContent='Workspace';$$('[style*="linear-gradient"].metric-card,[style*="linear-gradient"].card').forEach(x=>x.style.background='');}
  document.addEventListener('DOMContentLoaded',()=>setTimeout(install,180));
})();
