/* JUAN PROJECT Online — resilient in-house ads runtime */
(function(){"use strict";
var VISITOR_KEY="JUAN_VISITOR_ID_V1",SESSION_KEY="JUAN_AD_SESSION_V1",POPUP_SESSION_KEY="JUAN_POPUP_SHOWN_SESSION",data=null,bannerIndex=0,timer=null,impressed=new Set(),loadedAudience=null,lastLoadedAt=0,loadPromise=null;
function audienceMode(){return window.JuanSuiteRuntime.session()?.user?.id?"client":"guest"}
function adContext(){var route=window.JPOAppState?.route||"home",aud=audienceMode();if(route==="shop")return aud+"_shop";return aud+"_home"}
function placementMatches(ad,type){var p=String(ad.placement||""),ctx=adContext();if(p==="homepage_"+type)return ctx==="guest_home"||ctx==="client_home";return p===ctx+"_"+type}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function visitor(){var v=localStorage.getItem(VISITOR_KEY);if(!v){v=uid();localStorage.setItem(VISITOR_KEY,v)}return v}
function session(){var s=sessionStorage.getItem(SESSION_KEY);if(!s){s=uid();sessionStorage.setItem(SESSION_KEY,s)}return s}
async function api(body){return window.JuanSuiteRuntime.request("/api/suite",body)}
function event(ad,type,stable){try{var logged=window.JuanSuiteRuntime.session()?.user?.id||null;if(!logged&&localStorage.getItem("JUAN_PRIVACY_CONSENT_V1")!=="all")return;var viewer=logged||visitor(),key=stable?ad.id+":"+type+":"+viewer+":"+session():ad.id+":"+type+":"+viewer+":"+session()+":"+uid();api({action:"ad-event",ad_id:ad.id,visitor_id:logged?null:visitor(),session_id:session(),event_type:type,event_key:key}).catch(function(){})}catch(_){}}
function destination(ad){var type=ad.destination_type||"no_action",raw=String(ad.destination_value||""),value=raw.replace(/^#?/,"").toLowerCase();if(type==="no_action")return;if(type==="external_url"&&/^https:\/\//i.test(raw)){window.open(raw,"_blank","noopener");return}if(["shop","package","service"].includes(type)){document.querySelector('.nav [data-r="shop"]')?.click();return}if(["loyalty","referral"].includes(type)){document.querySelector('.nav [data-r="account"]')?.click();return}if(type==="page"){if(value==="track"){window.JPMobileCommerce?.openTrack?.();return}if(value==="login"){document.querySelector('[data-guest-action="login"]')?.click();return}var map={home:"home",orders:"orders",payment:"payment",payments:"payment",shop:"shop",account:"account",loyalty:"account",rewards:"account"};if(map[value])document.querySelector('.nav [data-r="'+map[value]+'"]')?.click()}}
function bannerSlot(){var anchor=document.getElementById("jpAdBannerAnchor");if(!anchor)return null;var slot=document.getElementById("jpHouseBanner");if(slot&&slot.isConnected)return slot;slot=document.createElement("div");slot.id="jpHouseBanner";slot.className="jp-house-banner";anchor.replaceChildren(slot);return slot}
function showBanner(ad){var slot=bannerSlot();if(!slot)return;slot.classList.remove("visible");requestAnimationFrame(function(){if(!slot.isConnected)return;slot.innerHTML='<button class="jp-banner-click" aria-label="'+String(ad.title||"Promotion").replace(/"/g,"&quot;")+'"><img src="'+String(ad.image||"").replace(/"/g,"&quot;")+'" alt="'+String(ad.image_alt||ad.title||"JUAN PROJECT promotion").replace(/"/g,"&quot;")+'"></button>';var img=slot.querySelector("img");img.onerror=function(){slot.innerHTML="";slot.classList.remove("visible")};slot.querySelector("button").onclick=function(){event(ad,"click",false);destination(ad)};requestAnimationFrame(function(){slot.classList.add("visible")});if(!impressed.has(ad.id)){impressed.add(ad.id);event(ad,"impression",true)}})}
function resetRotation(banners){if(timer)clearInterval(timer);timer=null;if(banners.length<2)return;var seconds=Math.max(3,Number(data?.settings?.rotation_seconds||8));timer=setInterval(function(){bannerIndex=(bannerIndex+1)%banners.length;showBanner(banners[bannerIndex])},seconds*1000)}
function mountBanners(){if(!data)return;var banners=(data.ads||[]).filter(function(a){return a.ad_type==="banner"&&placementMatches(a,"banner")&&a.image}).sort(function(a,b){return Number(b.priority||0)-Number(a.priority||0)});if(!banners.length){if(timer)clearInterval(timer);timer=null;document.getElementById("jpHouseBanner")?.remove();return}if(bannerIndex>=banners.length)bannerIndex=0;showBanner(banners[bannerIndex]);resetRotation(banners)}
function signalSettled(){window.__JUAN_AD_POPUP_ACTIVE=false;window.dispatchEvent(new Event("juan-ad-popup-settled"))}
function popup(){if(!data){signalSettled();return false}if(document.querySelector(".jp-popup-ad-overlay")){window.__JUAN_AD_POPUP_ACTIVE=true;return true}var popupKey=POPUP_SESSION_KEY+"_"+adContext();if(sessionStorage.getItem(popupKey)){signalSettled();return false}var list=(data.ads||[]).filter(function(a){return a.ad_type==="popup"&&placementMatches(a,"popup")&&a.image&&!localStorage.getItem("JUAN_AD_SEEN_"+a.id)}).sort(function(a,b){return Number(b.priority||0)-Number(a.priority||0)}),ad=list[0];if(!ad){signalSettled();return false}sessionStorage.setItem(popupKey,"1");localStorage.setItem("JUAN_AD_SEEN_"+ad.id,"1");window.__JUAN_AD_POPUP_ACTIVE=true;var layer=document.createElement("div");layer.className="jp-popup-ad-overlay";layer.innerHTML='<section class="jp-popup-ad" role="dialog" aria-modal="true" aria-label="'+String(ad.title||"Promotion").replace(/"/g,"&quot;")+'"><button class="jp-popup-close" aria-label="Close promotion">×</button><button class="jp-popup-image"><img src="'+String(ad.image).replace(/"/g,"&quot;")+'" alt="'+String(ad.image_alt||ad.title||"JUAN PROJECT promotion").replace(/"/g,"&quot;")+'"></button></section>';document.body.appendChild(layer);var close=function(kind){if(kind==="dismiss")event(ad,"dismiss",false);layer.classList.add("closing");setTimeout(function(){layer.remove();signalSettled()},150)};layer.querySelector(".jp-popup-close").onclick=function(){close("dismiss")};layer.addEventListener("click",function(e){if(e.target===layer)close("dismiss")});layer.querySelector(".jp-popup-image").onclick=function(){event(ad,"click",false);destination(ad);close("click")};layer.querySelector("img").onerror=function(){close("error")};event(ad,"impression",true);window.dispatchEvent(new Event("juan-ad-popup-open"));return true}
function render(){try{mountBanners();popup()}catch(e){console.warn("In-house ads render failed:",e?.message||e);signalSettled()}}
async function load(force){if(loadPromise)return loadPromise;if(!force&&data&&Date.now()-lastLoadedAt<15000){window.__JUAN_ADS_READY=true;render();return data}loadPromise=api({action:"ads"}).then(function(next){data=next;loadedAudience=audienceMode();lastLoadedAt=Date.now();window.__JUAN_ADS_READY=true;render();return data}).catch(function(e){console.warn("In-house ads unavailable:",e?.message||e);window.__JUAN_ADS_READY=true;signalSettled();return data}).finally(function(){loadPromise=null});return loadPromise}
window.addEventListener("juan-online-render",function(){if(loadedAudience!==audienceMode()||!data||Date.now()-lastLoadedAt>15000)load(true);else render()});window.addEventListener("juan-ads-refresh",function(){load(true)});document.addEventListener("visibilitychange",function(){if(document.hidden){if(timer)clearInterval(timer);timer=null}else if(!data||Date.now()-lastLoadedAt>30000)load(true);else render()});setInterval(function(){if(!document.hidden&&Date.now()-lastLoadedAt>60000)load(true)},30000);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(function(){load(true)},120)});else setTimeout(function(){load(true)},120);
})();