import {getSupabase,session,signIn,signUp,requestFirstAccess,setPassword,signOut} from './auth.js';import {getPortal,markPasswordSet} from './data.js';import {uploadReceipt,extractReceipt,submitPayment as submitPaymentApi} from './payments.js';import {peso,esc,fmtDate,remaining,toast} from './utils.js';
const root=document.getElementById('root');let state={route:'orders',portal:null,selected:null,receiptPath:null,extractedReceipt:null};
const nav=()=>`<nav class="nav"><button data-r="orders" class="${state.route==='orders'?'active':''}"><span class="icon">▣</span><span>Orders</span></button><button data-r="shop" class="${state.route==='shop'?'active':''}"><span class="icon">□</span><span>Shop</span></button><button data-r="payment" class="pay ${state.route==='payment'?'active':''}"><span>＋</span><span>Pay</span></button><button data-r="invoices" class="${state.route==='invoices'?'active':''}"><span class="icon">▤</span><span>Invoices</span></button><button data-r="account" class="${state.route==='account'?'active':''}"><span class="icon">⚙</span><span>Account</span></button></nav>`;
const top=(title,sub='')=>`<div class="topbar"><div><div class="brand">JUAN PROJECT<small>ONLINE</small></div></div><div class="avatar">${esc((state.portal?.profile?.name||state.portal?.profile?.email||'J').slice(0,2).toUpperCase())}</div></div><div class="eyebrow">${esc(sub)}</div><h1 class="title">${esc(title)}</h1>`;
function authScreen(mode='signin',message=''){if(mode==='first'){root.innerHTML=`<div class="auth-shell"><div class="auth-card"><div class="auth-hero"><div class="brand">JUAN PROJECT<small>ONLINE</small></div><h1>First access</h1><p class="subtitle">Use the same email registered with JUAN PROJECT. We’ll send a secure sign-in link, then you can set your password.</p></div><div class="field"><label>Email</label><input id="ae" class="input" type="email" autocomplete="email"></div><button id="ab" class="btn primary full">Send secure link</button><p class="helper">${esc(message)}</p><p class="helper"><a class="link" id="back">Back to Sign In</a></p></div></div>`;ab.onclick=async()=>{try{ab.disabled=true;await requestFirstAccess(ae.value.trim());localStorage.setItem('JUAN_FIRST_ACCESS','1');toast('Check your email for the secure link.');}catch(e){toast(e.message)}finally{ab.disabled=false}};back.onclick=()=>authScreen();return}
if(mode==='signup'){root.innerHTML=`<div class="auth-shell"><div class="auth-card"><div class="auth-hero"><div class="brand">JUAN PROJECT<small>ONLINE</small></div><h1>Create account</h1><p class="subtitle">For future clients. Existing JUAN PROJECT clients should use First Access instead.</p></div><div class="field"><label>Full name</label><input id="an" class="input"></div><div class="field"><label>Email</label><input id="ae" class="input" type="email"></div><div class="field"><label>Password</label><input id="ap" class="input" type="password" minlength="10"></div><button id="ab" class="btn primary full">Create Account</button><p class="helper">Use at least 10 characters. A passphrase is recommended.</p><p class="helper"><a class="link" id="back">Back to Sign In</a></p></div></div>`;ab.onclick=async()=>{try{if(ap.value.length<10)throw Error('Password must be at least 10 characters.');ab.disabled=true;const d=await signUp({name:an.value.trim(),email:ae.value.trim(),password:ap.value});if(d.session){await loadPortal();}else toast('Check your email to confirm the account.')}catch(e){toast(e.message)}finally{ab.disabled=false}};back.onclick=()=>authScreen();return}
root.innerHTML=`<div class="auth-shell"><div class="auth-card"><div class="auth-hero"><div class="brand">JUAN PROJECT<small>ONLINE</small></div><h1>Your projects. In one place.</h1><p class="subtitle">Track deliverables, open shared files, review invoices, and submit payments.</p></div><div class="field"><label>Email</label><input id="ae" class="input" type="email" autocomplete="username"></div><div class="field"><label>Password</label><input id="ap" class="input" type="password" autocomplete="current-password"></div><div class="auth-actions"><button id="ab" class="btn primary full">Sign In</button><button id="first" class="btn full">First Access / Set Password</button><button id="newc" class="btn full">Create Future Client Account</button></div><p class="helper">${esc(message)}</p></div></div>`;ab.onclick=async()=>{try{ab.disabled=true;await signIn(ae.value.trim(),ap.value);await loadPortal()}catch(e){toast(e.message)}finally{ab.disabled=false}};first.onclick=()=>authScreen('first');newc.onclick=()=>authScreen('signup')}
async function loadPortal(){try{state.portal=await getPortal();if(!state.portal.passwordSet){return renderSetPassword()}localStorage.removeItem('JUAN_FIRST_ACCESS');state.route='orders';render()}catch(e){authScreen('signin',e.message)}}
function renderSetPassword(){root.innerHTML=`<div class="auth-shell"><div class="auth-card"><div class="brand">JUAN PROJECT<small>ONLINE</small></div><h1 class="title" style="margin-top:30px">Create your password</h1><p class="subtitle">Your email has been verified. Add a password for your next sign-in.</p><div class="field"><label>New password</label><input id="p1" class="input" type="password" minlength="10"></div><div class="field"><label>Confirm password</label><input id="p2" class="input" type="password" minlength="10"></div><button id="savep" class="btn primary full">Set Password</button></div></div>`;savep.onclick=async()=>{try{if(p1.value.length<10)throw Error('Use at least 10 characters.');if(p1.value!==p2.value)throw Error('Passwords do not match.');await setPassword(p1.value);await markPasswordSet();localStorage.removeItem('JUAN_FIRST_ACCESS');toast('Password created.');await loadPortal()}catch(e){toast(e.message)}}}
function routePage(){if(state.route==='orders')return orders();if(state.route==='project')return project();if(state.route==='payment')return payment();if(state.route==='invoices')return invoices();if(state.route==='invoice')return invoice();if(state.route==='account')return account();return shop()}
function render(){root.innerHTML=`<div class="app"><main class="page">${routePage()}</main>${nav()}</div>`;document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{state.route=b.dataset.r;state.selected=null;render()});bind()}
function projectStats(p){const ds=p.deliverables||[];const done=ds.filter(x=>x.completed||String(x.status||'').toLowerCase()==='completed').length;return {done,total:ds.length,pct:ds.length?Math.round(done/ds.length*100):0}}
function orders(){const ps=state.portal.projects||[];return `${top('Orders','Your projects')}<p class="subtitle">Track every active and completed JUAN PROJECT order.</p>${ps.map(p=>{const s=projectStats(p);return `<div class="card project-card" data-open="${esc(p.id)}"><div class="project-head"><div><div class="project-code">${esc(p.project_code||p.id)}</div><div class="project-name">${esc(p.title||'Untitled Project')}</div><div class="helper">${esc(fmtDate(p.deadline_date))}</div></div><span class="badge">${esc(p.status||'Active')}</span></div><div class="progress"><span style="width:${s.pct}%"></span></div><div class="meta"><span>${s.done} of ${s.total} deliverables</span><b>${s.pct}%</b></div></div>`}).join('')||'<div class="card coming"><b>No orders yet.</b><p class="helper">New projects linked to this account will appear here.</p></div>'}`}
function project(){const p=(state.portal.projects||[]).find(x=>x.id===state.selected);if(!p){state.route='orders';return orders()}const s=projectStats(p);return `${top(p.title,p.project_code||p.id)}<button class="btn small" id="backOrders">← Orders</button><div class="card" style="margin-top:14px"><div class="row"><b>Project progress</b><b>${s.pct}%</b></div><div class="progress"><span style="width:${s.pct}%"></span></div><div class="meta"><span>${s.done} / ${s.total} completed</span><span>${esc(remaining(p.deadline_date))}</span></div></div><div class="card"><b>Deliverables</b><div>${(p.deliverables||[]).map(d=>`<div class="deliverable"><span class="dot ${d.completed?'done':''}">${d.completed?'✓':''}</span><div><div class="d-name">${esc(d.item_name||d.name||'Deliverable')}</div><div class="d-sub">${esc(d.status|| (d.completed?'Completed':'Pending'))} · ${esc(remaining(d.due_date||p.deadline_date))}</div></div>${d.shared_drive_url?`<button class="drive" data-drive="${esc(d.shared_drive_url)}" aria-label="Open shared Google Drive file">↗</button>`:''}</div>`).join('')||'<div class="helper" style="padding-top:14px">No deliverables yet.</div>'}</div></div><div class="card"><div class="row"><div><b>Payment</b><div class="helper">Balance for this project</div></div><div style="text-align:right"><div class="money" style="font-size:19px">${peso(p.balance)}</div><button class="btn small primary" id="payProject">Pay</button></div></div></div>`}
function payment(){const settings=state.portal.paymentSettings||{};const ps=(state.portal.projects||[]).filter(p=>Number(p.balance||0)>0);return `${top('Payment','Submit a payment')}<div class="card balance"><div class="eyebrow">TOTAL BALANCE</div><div class="money">${peso(ps.reduce((s,p)=>s+Number(p.balance||0),0))}</div></div><div class="card"><b>Scan to Pay</b><p class="helper">${esc(settings.instructions||'Use the payment account below, then upload your receipt for approval.')}</p>${settings.qr_image_url?`<img class="qr" src="${esc(settings.qr_image_url)}" alt="Payment QR code">`:'<div class="upload">QR code will appear here when configured by JUAN PROJECT.</div>'}<div class="row"><span>${esc(settings.method_label||'Payment')}</span><b>${esc(settings.account_number||'')}</b></div><div class="helper" style="margin-top:5px">${esc(settings.account_name||'')}</div></div><div class="card"><b>Submit Payment</b><div class="field" style="margin-top:14px"><label>Project</label><select id="payProjectSel" class="input">${ps.map(p=>`<option value="${esc(p.id)}">${esc(p.project_code||p.id)} · ${esc(p.title)} · ${peso(p.balance)}</option>`).join('')}</select></div><div class="field"><label>Amount</label><input id="payAmount" class="input" type="number" min="1" step="0.01"></div><div class="field"><label>Method</label><input id="payMethod" class="input" value="${esc(settings.method_label||'GCash')}"></div><div class="field"><label>Reference number</label><input id="payRef" class="input" placeholder="Can be read from receipt"></div><div class="field"><label>Date paid</label><input id="payDate" class="input" type="date" value="${new Date().toISOString().slice(0,10)}"></div><label class="upload" for="receipt"><input id="receipt" type="file" accept="image/jpeg,image/png,application/pdf" hidden><b id="receiptLabel">Tap to upload receipt</b><div class="helper">JPG, PNG, or PDF · max 5 MB</div></label><button id="readReceipt" class="btn full" style="margin-top:10px" disabled>Read Receipt with AI</button><button id="submitPayment" class="btn primary full" style="margin-top:10px" ${ps.length?'':'disabled'}>Submit for Approval</button></div>${paymentHistory()}`}
function paymentHistory(){const rows=state.portal.paymentSubmissions||[];return `<div class="card flat"><div style="padding:17px"><b>Submitted Payments</b></div><div class="table-list">${rows.map(x=>`<div class="list-row"><div class="row"><div><b>${peso(x.submitted_amount)}</b><div class="helper">${esc(x.reference_number||x.extracted_reference||'No reference')} · ${fmtDate(x.payment_date||x.submitted_at)}</div></div><span class="badge ${x.status==='pending'?'pending':''}">${esc(x.status)}</span></div></div>`).join('')||'<div class="list-row helper">No client-submitted payments yet.</div>'}</div></div>`}
function invoices(){const ps=state.portal.projects||[];return `${top('Invoices','Project billing')}<p class="subtitle">View the same project totals and approved payments recorded by JUAN PROJECT Workspace.</p>${ps.map(p=>`<div class="card project-card" data-invoice="${esc(p.id)}"><div class="row"><div><div class="project-code">${esc(p.project_code||p.id)}</div><b>${esc(p.title)}</b><div class="helper">${esc(p.payment_status||'')}</div></div><div style="text-align:right"><b>${peso(p.total_amount)}</b><div class="helper">Balance ${peso(p.balance)}</div></div></div></div>`).join('')||'<div class="card">No invoices yet.</div>'}`}
function invoice(){const p=(state.portal.projects||[]).find(x=>x.id===state.selected);if(!p){state.route='invoices';return invoices()}return `${top('Invoice',p.project_code||p.id)}<button class="btn small" id="backInvoices">← Invoices</button><div class="invoice" style="margin-top:14px"><div class="invoice-h"><div><div class="brand">JUAN PROJECT</div><div class="helper">Creative services</div></div><div style="text-align:right"><div class="eyebrow">INVOICE</div><b>${esc('INV-'+String(p.project_code||p.id).replace('JP-',''))}</b><div><span class="badge">${esc(p.payment_status||'UNPAID')}</span></div></div></div><div class="invoice-grid"><div><div class="eyebrow">BILL TO</div><b>${esc(state.portal.profile.name||state.portal.profile.email)}</b><div class="helper">${esc(state.portal.profile.email||'')}</div></div><div><div class="eyebrow">PROJECT</div><b>${esc(p.title)}</b><div class="helper">Due ${esc(fmtDate(p.deadline_date))}</div></div></div><table><thead><tr><th>ORDER ITEM</th><th>QTY</th><th>AMOUNT</th></tr></thead><tbody>${(p.items||[]).map(i=>`<tr><td>${esc(i.name||'Item')}</td><td>${Number(i.qty||1)}</td><td>${peso(Number(i.price||0)*Number(i.qty||1))}</td></tr>`).join('')||`<tr><td>${esc(p.title)}</td><td>1</td><td>${peso(p.total_amount)}</td></tr>`}</tbody></table><div class="invoice-total"><div class="row"><span>Total</span><b>${peso(p.total_amount)}</b></div><div class="row"><span>Amount Paid</span><b>${peso(p.amount_paid)}</b></div><div class="card balance"><div class="eyebrow">BALANCE DUE</div><div class="money">${peso(p.balance)}</div></div></div></div>`}
function account(){return `${top('Account','Settings')}<div class="card"><b>${esc(state.portal.profile.name||'Client')}</b><div class="helper">${esc(state.portal.profile.email||'')}</div><div class="helper">${esc(state.portal.profile.client_code||'')}</div></div><div class="card"><b>Change Password</b><div class="field" style="margin-top:14px"><label>New password</label><input id="newPass" class="input" type="password" minlength="10"></div><div class="field"><label>Confirm password</label><input id="newPass2" class="input" type="password" minlength="10"></div><button id="changePass" class="btn full">Update Password</button></div><button id="logout" class="btn full">Sign Out</button>`}
function shop(){return `${top('Shop','Coming soon')}<div class="card coming"><div class="icon-big">＋</div><h2>JUAN PROJECT Shop is coming soon.</h2><p class="subtitle">Your account and project portal are ready first. Services and packages will use the same catalog managed from JUAN PROJECT Workspace.</p></div>`}
function bind(){
  document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>{state.selected=x.dataset.open;state.route='project';render()});
  document.querySelectorAll('[data-invoice]').forEach(x=>x.onclick=()=>{state.selected=x.dataset.invoice;state.route='invoice';render()});
  document.querySelectorAll('[data-drive]').forEach(x=>x.onclick=()=>window.open(x.dataset.drive,'_blank','noopener'));
  const backOrders=document.getElementById('backOrders'); if(backOrders) backOrders.onclick=()=>{state.route='orders';render()};
  const payProject=document.getElementById('payProject'); if(payProject) payProject.onclick=()=>{state.route='payment';render()};
  const backInvoices=document.getElementById('backInvoices'); if(backInvoices) backInvoices.onclick=()=>{state.route='invoices';render()};
  const receipt=document.getElementById('receipt');
  const receiptLabel=document.getElementById('receiptLabel');
  const readBtn=document.getElementById('readReceipt');
  if(receipt) receipt.onchange=async()=>{const f=receipt.files?.[0];if(!f)return;try{state.extractedReceipt=null;state.receiptPath=await uploadReceipt(f);if(receiptLabel)receiptLabel.textContent='Receipt uploaded';if(readBtn)readBtn.disabled=false;toast('Receipt uploaded securely.')}catch(e){toast(e.message)}};
  if(readBtn) readBtn.onclick=async()=>{try{readBtn.disabled=true;readBtn.textContent='Reading…';const x=await extractReceipt(state.receiptPath);state.extractedReceipt=x;const ref=document.getElementById('payRef'),amt=document.getElementById('payAmount'),date=document.getElementById('payDate'),method=document.getElementById('payMethod');if(x.referenceNumber&&ref)ref.value=x.referenceNumber;if(x.amount&&amt)amt.value=x.amount;if(x.paymentDate&&date)date.value=x.paymentDate;if(x.paymentMethod&&method)method.value=x.paymentMethod;toast('Receipt details prefilled. Please review them.')}catch(e){toast(e.message)}finally{readBtn.disabled=false;readBtn.textContent='Read Receipt with AI'}};
  const submitBtn=document.getElementById('submitPayment');
  if(submitBtn) submitBtn.onclick=async()=>{try{if(!state.receiptPath)throw Error('Upload a receipt first.');const amt=document.getElementById('payAmount'),projectSel=document.getElementById('payProjectSel'),method=document.getElementById('payMethod'),ref=document.getElementById('payRef'),date=document.getElementById('payDate');const amount=Number(amt?.value||0);if(!(amount>0))throw Error('Enter the amount paid.');submitBtn.disabled=true;await submitPaymentFn({projectId:projectSel?.value,amount,paymentMethod:method?.value||'',referenceNumber:ref?.value||'',paymentDate:date?.value||'',receiptPath:state.receiptPath,extracted:state.extractedReceipt});toast('Payment submitted for approval.');state.portal=await getPortal();state.receiptPath=null;state.extractedReceipt=null;render()}catch(e){toast(e.message)}finally{if(document.body.contains(submitBtn))submitBtn.disabled=false}};
  const changeBtn=document.getElementById('changePass');
  if(changeBtn) changeBtn.onclick=async()=>{try{const p1=document.getElementById('newPass'),p2=document.getElementById('newPass2');if((p1?.value||'').length<10)throw Error('Use at least 10 characters.');if(p1.value!==p2.value)throw Error('Passwords do not match.');await setPassword(p1.value);await markPasswordSet();toast('Password updated.');p1.value=p2.value=''}catch(e){toast(e.message)}};
  const logoutBtn=document.getElementById('logout'); if(logoutBtn) logoutBtn.onclick=async()=>{await signOut();state.portal=null;authScreen()};
}
async function submitPaymentFn(body){return submitPaymentApi(body)}
(async()=>{try{await getSupabase();const s=await session();if(s)await loadPortal();else authScreen()}catch(e){authScreen('signin',e.message)}})();
