-- JUAN PROJECT Platform V1.3.3.2 — Realtime Sync Bus
-- Keeps Workspace ↔ Online Portal and Workspace ↔ Workspace data fresh through
-- Supabase Realtime without exposing private business rows directly to clients.

begin;

create table if not exists public.workspace_shared_state (
  id integer primary key default 1 check (id=1),
  tasks jsonb not null default '[]'::jsonb,
  templates jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);
insert into public.workspace_shared_state(id) values(1) on conflict(id) do nothing;
alter table public.workspace_shared_state enable row level security;
drop policy if exists juan_admin_workspace_shared_state on public.workspace_shared_state;
create policy juan_admin_workspace_shared_state
on public.workspace_shared_state
for all
to authenticated
using (public.is_juan_admin())
with check (public.is_juan_admin());
grant select,insert,update on public.workspace_shared_state to authenticated;

create table if not exists public.juan_sync_events (
  id bigint generated by default as identity primary key,
  audience text not null default 'admin' check (audience in ('admin','client','global')),
  client_id text null,
  entity text not null,
  entity_id text null,
  action text not null check (action in ('INSERT','UPDATE','DELETE')),
  occurred_at timestamptz not null default now()
);

create index if not exists juan_sync_events_occurred_at_idx
  on public.juan_sync_events (occurred_at desc);
create index if not exists juan_sync_events_client_idx
  on public.juan_sync_events (client_id, occurred_at desc)
  where client_id is not null;

alter table public.juan_sync_events enable row level security;

drop policy if exists juan_sync_events_admin_read on public.juan_sync_events;
create policy juan_sync_events_admin_read
on public.juan_sync_events
for select
to authenticated
using (public.is_juan_admin());

drop policy if exists juan_sync_events_client_read on public.juan_sync_events;
create policy juan_sync_events_client_read
on public.juan_sync_events
for select
to authenticated
using (
  audience='global'
  or (
    audience='client'
    and client_id is not null
    and exists (
      select 1
      from public.portal_accounts a
      where a.auth_user_id=auth.uid()
        and a.client_id=juan_sync_events.client_id
    )
  )
);

grant select on public.juan_sync_events to authenticated;

create or replace function public.juan_emit_sync_event()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  row_data jsonb;
  v_client_id text;
  v_project_id text;
  v_entity_id text;
  v_audience text := 'admin';
begin
  if tg_op='DELETE' then row_data := to_jsonb(old); else row_data := to_jsonb(new); end if;

  v_entity_id := coalesce(
    row_data->>'id',
    row_data->>'auth_user_id',
    row_data->>'project_id',
    row_data->>'client_id'
  );

  if tg_table_name='clients' then
    v_client_id := row_data->>'id';
    v_audience := case when v_client_id is null then 'admin' else 'client' end;
  elsif tg_table_name='projects' then
    v_client_id := row_data->>'client_id';
    v_audience := case when v_client_id is null then 'admin' else 'client' end;
  elsif tg_table_name in ('deliverables','project_items','payments') then
    v_project_id := row_data->>'project_id';
    if v_project_id is not null then
      select p.client_id into v_client_id from public.projects p where p.id=v_project_id limit 1;
    end if;
    v_audience := case when v_client_id is null then 'admin' else 'client' end;
  elsif tg_table_name='payment_submissions' then
    v_client_id := row_data->>'client_id';
    v_audience := case when v_client_id is null then 'admin' else 'client' end;
  elsif tg_table_name='portal_accounts' then
    v_client_id := row_data->>'client_id';
    v_audience := case when v_client_id is null then 'admin' else 'client' end;
  elsif tg_table_name in ('payment_settings','catalog_categories','catalog_services','catalog_packages','catalog_package_items') then
    v_audience := 'global';
  else
    v_audience := 'admin';
  end if;

  insert into public.juan_sync_events(audience,client_id,entity,entity_id,action)
  values(v_audience,v_client_id,tg_table_name,v_entity_id,tg_op);

  -- Keep the event table bounded without requiring a scheduled job.
  if random() < 0.01 then
    delete from public.juan_sync_events where occurred_at < now() - interval '14 days';
  end if;

  if tg_op='DELETE' then return old; end if;
  return new;
end;
$$;

revoke all on function public.juan_emit_sync_event() from public;

-- Add one lightweight trigger to every table whose mutation can change what a
-- Workspace or client portal sees. Dynamic DDL keeps this migration safe across
-- older installs where an optional table may not exist yet.
do $$
declare
  t text;
  trigger_name text;
begin
  foreach t in array array[
    'clients','projects','deliverables','project_items','payments',
    'payment_submissions','portal_accounts','payment_settings',
    'catalog_categories','catalog_services','catalog_packages','catalog_package_items',
    'workspace_settings','workspace_shared_state','order_drafts'
  ] loop
    if to_regclass('public.'||t) is not null then
      trigger_name := 'juan_sync_'||t||'_trigger';
      execute format('drop trigger if exists %I on public.%I', trigger_name, t);
      execute format(
        'create trigger %I after insert or update or delete on public.%I for each row execute function public.juan_emit_sync_event()',
        trigger_name,
        t
      );
    end if;
  end loop;
end $$;

-- Supabase Realtime only streams tables that are in the supabase_realtime publication.
do $$
begin
  if exists(select 1 from pg_publication where pubname='supabase_realtime')
     and not exists(
       select 1 from pg_publication_tables
       where pubname='supabase_realtime'
         and schemaname='public'
         and tablename='juan_sync_events'
     ) then
    alter publication supabase_realtime add table public.juan_sync_events;
  end if;
end $$;

commit;
