-- Production migration for JUAN PROJECT guest ordering, QR/client cards, tracking and portal tools.
alter table public.clients add column if not exists classification text not null default 'New', add column if not exists qr_token text;
do $$ begin alter table public.clients add constraint clients_classification_check check (classification in ('New','Returning','Loyal','VIP')); exception when duplicate_object then null; end $$;
create unique index if not exists clients_qr_token_uidx on public.clients(qr_token) where qr_token is not null;

alter table public.projects add column if not exists tracker_stage integer not null default 0, add column if not exists milestones jsonb not null default '[]'::jsonb, add column if not exists files_override boolean not null default false;
do $$ begin alter table public.projects add constraint projects_tracker_stage_check check (tracker_stage between 0 and 6); exception when duplicate_object then null; end $$;

create table if not exists public.incoming_orders(
 id uuid primary key default gen_random_uuid(), order_number bigint generated by default as identity unique, code text unique,
 name text not null,email text not null,phone text,title text not null,notes text not null default '',deadline date,
 items jsonb not null default '[]'::jsonb,subtotal numeric(12,2) not null default 0,rush_fee numeric(12,2) not null default 0,total numeric(12,2) not null default 0,
 status text not null default 'Order Received',submission_key text not null unique,token_hash text not null unique,review_note text not null default '',
 project_id text references public.projects(id) on delete set null,client_id text references public.clients(id) on delete set null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
do $$ begin alter table public.incoming_orders add constraint incoming_orders_status_check check (status in ('Order Received','Under Review','Needs Changes','Approved','Rejected')); exception when duplicate_object then null; end $$;
create or replace function public.assign_juan_guest_order_code() returns trigger language plpgsql set search_path=public as $$ begin if new.code is null or btrim(new.code)='' then new.code:='GO-'||lpad(new.order_number::text,3,'0'); end if; return new; end $$;
drop trigger if exists incoming_orders_assign_code on public.incoming_orders;
create trigger incoming_orders_assign_code before insert or update of code on public.incoming_orders for each row execute function public.assign_juan_guest_order_code();
drop trigger if exists incoming_orders_set_updated_at on public.incoming_orders;
create trigger incoming_orders_set_updated_at before update on public.incoming_orders for each row execute function public.set_updated_at();

create table if not exists public.promotions(id uuid primary key default gen_random_uuid(),title text not null,body text not null default '',cta text not null default 'Browse services',url text,image text,audience text not null default 'all',start_date date,end_date date,enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
do $$ begin alter table public.promotions add constraint promotions_audience_check check (audience in ('all','guest','client')); exception when duplicate_object then null; end $$;
drop trigger if exists promotions_set_updated_at on public.promotions;
create trigger promotions_set_updated_at before update on public.promotions for each row execute function public.set_updated_at();

create table if not exists public.portal_invitations(id uuid primary key default gen_random_uuid(),client_id text not null references public.clients(id) on delete cascade,token text not null unique,status text not null default 'pending',expires_at timestamptz not null default (now()+interval '7 days'),accepted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
do $$ begin alter table public.portal_invitations add constraint portal_invitations_status_check check(status in ('pending','accepted','revoked','expired')); exception when duplicate_object then null; end $$;
drop trigger if exists portal_invitations_set_updated_at on public.portal_invitations;
create trigger portal_invitations_set_updated_at before update on public.portal_invitations for each row execute function public.set_updated_at();

create table if not exists public.portal_activity(id uuid primary key default gen_random_uuid(),title text not null,entity text,actor_user_id uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.suite_config(id smallint primary key default 1 check(id=1),online_url text,workspace_url text,rules jsonb not null default '{"maribank":"^\\d{6,12}$"}'::jsonb,updated_at timestamptz not null default now());
insert into public.suite_config(id,online_url,workspace_url) values(1,'https://juan-project-online.vercel.app','https://juan-project-workspace-v2.vercel.app') on conflict(id) do nothing;
drop trigger if exists suite_config_set_updated_at on public.suite_config;
create trigger suite_config_set_updated_at before update on public.suite_config for each row execute function public.set_updated_at();

alter table public.incoming_orders enable row level security; alter table public.promotions enable row level security; alter table public.portal_invitations enable row level security; alter table public.portal_activity enable row level security; alter table public.suite_config enable row level security;
drop policy if exists incoming_orders_admin_all on public.incoming_orders; create policy incoming_orders_admin_all on public.incoming_orders for all to authenticated using(public.is_juan_admin()) with check(public.is_juan_admin());
drop policy if exists promotions_admin_all on public.promotions; create policy promotions_admin_all on public.promotions for all to authenticated using(public.is_juan_admin()) with check(public.is_juan_admin());
drop policy if exists portal_invitations_admin_all on public.portal_invitations; create policy portal_invitations_admin_all on public.portal_invitations for all to authenticated using(public.is_juan_admin()) with check(public.is_juan_admin());
drop policy if exists portal_activity_admin_read on public.portal_activity; create policy portal_activity_admin_read on public.portal_activity for select to authenticated using(public.is_juan_admin());
drop policy if exists suite_config_admin_all on public.suite_config; create policy suite_config_admin_all on public.suite_config for all to authenticated using(public.is_juan_admin()) with check(public.is_juan_admin());
grant select,insert,update,delete on public.incoming_orders,public.promotions,public.portal_invitations,public.suite_config to authenticated; grant select on public.portal_activity to authenticated;
create index if not exists incoming_orders_created_idx on public.incoming_orders(created_at desc); create index if not exists incoming_orders_status_idx on public.incoming_orders(status); create index if not exists incoming_orders_client_idx on public.incoming_orders(client_id); create index if not exists portal_invitations_client_idx on public.portal_invitations(client_id); create index if not exists portal_activity_created_idx on public.portal_activity(created_at desc);
